# Setup

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!pip install -qU transformers datasets optimum
!pip install -qU openai wandb

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 83.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 527.0/527.0 kB 38.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.2/161.2 kB 13.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 MB 24.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 23.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.2/27.2 MB 76.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.3/47.3 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 42.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.9/87.9 kB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 433.1/433.1 MB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.3/194.3 kB 20.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 267.7/267.7 MB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 122.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.0/111.0 kB 13.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.4/45.4 kB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 127.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 78.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 662.1/662.1 kB 53.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.2/114.2 kB 13.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 109.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.5/6.5 MB 125.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.4/121.4 kB 14.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 94.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.4/74.4 MB 10.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 108.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.1/72.1 kB 9.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 180.2/180.2 kB 22.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.0/69.0 kB 8.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 231.6/231.6 kB 25.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 240.0/240.0 kB 30.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 71.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.2/42.2 MB 20.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 388.0/388.0 kB 39.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.2/288.2 kB 26.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.7/149.7 kB 18.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 225.0/225.0 kB 23.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 180.7/180.7 kB 20.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 8.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 114.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.4/42.4 MB 19.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 9.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 320.7/320.7 kB 36.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 897.8/897.8 kB 74.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 30.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 106.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 819.4/819.4 kB 67.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 959.8/959.8 kB 69.2 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
google-adk 1.29.0 requires opentelemetry-api<1.39.0,>=1.36.0, but you have opentelemetry-api 1.41.1 which is incompatible.
google-adk 1.29.0 requires opentelemetry-sdk<1.39.0,>=1.36.0, but you have opentelemetry-sdk 1.41.1 which is incompatible.
opentelemetry-exporter-gcp-logging 1.11.0a0 requires opentelemetry-sdk<1.39.0,>=1.35.0, but you have opentelemetry-sdk 1.41.1 which is incompatible.

In [ ]:
!git clone --depth 1 https://github.com/hiyouga/LLaMA-Factory.git
!cd LLaMA-Factory && pip install -e .

Cloning into 'LLaMA-Factory'...
remote: Enumerating objects: 654, done.
remote: Counting objects: 100% (654/654), done.
remote: Compressing objects: 100% (492/492), done.
remote: Total 654 (delta 156), reused 420 (delta 101), pack-reused 0 (from 0)
Receiving objects: 100% (654/654), 5.29 MiB | 7.25 MiB/s, done.
Resolving deltas: 100% (156/156), done.
Obtaining file:///content/LLaMA-Factory
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting accelerate<=1.11.0,>=1.3.0 (from llamafactory==0.9.5.dev0)
  Downloading accelerate-1.11.0-py3-none-any.whl.metadata (19 kB)
Collecting av<=16.0.0,>=10.0.0 (from llamafactory==0.9.5.dev0)
  Downloading av-16.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (4.6 kB)
Collecting datasets<=4.0.0,>=2.16.0 (from llamafactory==0.9.5.dev0)
  Downloading datasets-4.0.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from llamafactory==0.9.5.dev0) (0.8.2)
Requirement already satisfied: fastapi in /usr/local/lib/python3.12/dist-packages (from llamafactory==0.9.5.dev0) (0.135.3)
Collecting fire (from llamafactory==0.9.5.dev0)
  Downloading fire-0.7.1-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: gradio<=5.50.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from llamafactory==0.9.5.dev0) (5.50.0)
Collecting hf-transfer (from llamafactory==0.9.5.dev0)
  Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: matplotlib>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from llamafactory==0.9.5.dev0) (3.10.0)
Collecting modelscope (from llamafactory==0.9.5.dev0)
  Downloading modelscope-1.36.2-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.5/43.5 kB 4.1 MB/s eta 0:00:00
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from llamafactory==0.9.5.dev0) (2.0.2)
Requirement already satisfied: omegaconf in /usr/local/lib/python3.12/dist-packages (from llamafactory==0.9.5.dev0) (2.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from llamafactory==0.9.5.dev0) (26.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from llamafactory==0.9.5.dev0) (2.2.2)
Requirement already satisfied: peft<=0.18.1,>=0.18.0 in /usr/local/lib/python3.12/dist-packages (from llamafactory==0.9.5.dev0) (0.18.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from llamafactory==0.9.5.dev0) (5.29.6)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from llamafactory==0.9.5.dev0) (2.12.3)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from llamafactory==0.9.5.dev0) (6.0.3)
Requirement already satisfied: safetensors in /usr/local/lib/python3.12/dist-packages (from llamafactory==0.9.5.dev0) (0.7.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from llamafactory==0.9.5.dev0) (1.16.3)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (from llamafactory==0.9.5.dev0) (0.2.1)
Requirement already satisfied: sse-starlette in /usr/local/lib/python3.12/dist-packages (from llamafactory==0.9.5.dev0) (3.3.4)
Requirement already satisfied: tiktoken in /usr/local/lib/python3.12/dist-packages (from llamafactory==0.9.5.dev0) (0.12.0)
Requirement already satisfied: torch>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from llamafactory==0.9.5.dev0) (2.10.0+cu128)
Requirement already satisfied: torchaudio>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from llamafactory==0.9.5.dev0) (2.10.0+cu128)
Requirement already satisfied: torchdata<=0.11.0,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from llamafactory==0.9.5.dev0) (0.11.0)
Requirement already satisfied: torchvision>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from llamafactory==0.9.5.dev0) (0.25.0+cu128)
Collecting transformers!=4.52.0,!=4.57.0,<=5.2.0,>=4.55.0 (from llamafactory==0.9.5.dev0)
  Downloading transformers-5.2.0-py3-none-any.whl.metadata (32 kB)
Collecting trl<=0.24.0,>=0.18.0 (from llamafactory==0.9.5.dev0)
  Downloading trl-0.24.0-py3-none-any.whl.metadata (11 kB)
Collecting tyro<0.9.0 (from llamafactory==0.9.5.dev0)
  Downloading tyro-0.8.14-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: uvicorn in /usr/local/lib/python3.12/dist-packages (from llamafactory==0.9.5.dev0) (0.44.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate<=1.11.0,>=1.3.0->llamafactory==0.9.5.dev0) (5.9.5)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from accelerate<=1.11.0,>=1.3.0->llamafactory==0.9.5.dev0) (1.10.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets<=4.0.0,>=2.16.0->llamafactory==0.9.5.dev0) (3.25.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets<=4.0.0,>=2.16.0->llamafactory==0.9.5.dev0) (24.0.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets<=4.0.0,>=2.16.0->llamafactory==0.9.5.dev0) (0.3.8)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets<=4.0.0,>=2.16.0->llamafactory==0.9.5.dev0) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets<=4.0.0,>=2.16.0->llamafactory==0.9.5.dev0) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets<=4.0.0,>=2.16.0->llamafactory==0.9.5.dev0) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets<=4.0.0,>=2.16.0->llamafactory==0.9.5.dev0) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets<=4.0.0,>=2.16.0->llamafactory==0.9.5.dev0) (2025.3.0)
Requirement already satisfied: aiofiles<25.0,>=22.0 in /usr/local/lib/python3.12/dist-packages (from gradio<=5.50.0,>=4.38.0->llamafactory==0.9.5.dev0) (24.1.0)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio<=5.50.0,>=4.38.0->llamafactory==0.9.5.dev0) (4.13.0)
Requirement already satisfied: brotli>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from gradio<=5.50.0,>=4.38.0->llamafactory==0.9.5.dev0) (1.2.0)
Requirement already satisfied: ffmpy in /usr/local/lib/python3.12/dist-packages (from gradio<=5.50.0,>=4.38.0->llamafactory==0.9.5.dev0) (1.0.0)
Requirement already satisfied: gradio-client==1.14.0 in /usr/local/lib/python3.12/dist-packages (from gradio<=5.50.0,>=4.38.0->llamafactory==0.9.5.dev0) (1.14.0)
Requirement already satisfied: groovy~=0.1 in /usr/local/lib/python3.12/dist-packages (from gradio<=5.50.0,>=4.38.0->llamafactory==0.9.5.dev0) (0.1.2)
Requirement already satisfied: httpx<1.0,>=0.24.1 in /usr/local/lib/python3.12/dist-packages (from gradio<=5.50.0,>=4.38.0->llamafactory==0.9.5.dev0) (0.28.1)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.12/dist-packages (from gradio<=5.50.0,>=4.38.0->llamafactory==0.9.5.dev0) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio<=5.50.0,>=4.38.0->llamafactory==0.9.5.dev0) (3.0.3)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio<=5.50.0,>=4.38.0->llamafactory==0.9.5.dev0) (3.11.8)
Requirement already satisfied: pillow<12.0,>=8.0 in /usr/local/lib/python3.12/dist-packages (from gradio<=5.50.0,>=4.38.0->llamafactory==0.9.5.dev0) (11.3.0)
Requirement already satisfied: pydub in /usr/local/lib/python3.12/dist-packages (from gradio<=5.50.0,>=4.38.0->llamafactory==0.9.5.dev0) (0.25.1)
Requirement already satisfied: python-multipart>=0.0.18 in /usr/local/lib/python3.12/dist-packages (from gradio<=5.50.0,>=4.38.0->llamafactory==0.9.5.dev0) (0.0.26)
Requirement already satisfied: ruff>=0.9.3 in /usr/local/lib/python3.12/dist-packages (from gradio<=5.50.0,>=4.38.0->llamafactory==0.9.5.dev0) (0.15.10)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.6 in /usr/local/lib/python3.12/dist-packages (from gradio<=5.50.0,>=4.38.0->llamafactory==0.9.5.dev0) (0.1.7)
Requirement already satisfied: semantic-version~=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio<=5.50.0,>=4.38.0->llamafactory==0.9.5.dev0) (2.10.0)
Requirement already satisfied: starlette<1.0,>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from gradio<=5.50.0,>=4.38.0->llamafactory==0.9.5.dev0) (0.52.1)
Requirement already satisfied: tomlkit<0.14.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from gradio<=5.50.0,>=4.38.0->llamafactory==0.9.5.dev0) (0.13.3)
Requirement already satisfied: typer<1.0,>=0.12 in /usr/local/lib/python3.12/dist-packages (from gradio<=5.50.0,>=4.38.0->llamafactory==0.9.5.dev0) (0.24.1)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.12/dist-packages (from gradio<=5.50.0,>=4.38.0->llamafactory==0.9.5.dev0) (4.15.0)
Requirement already satisfied: websockets<16.0,>=13.0 in /usr/local/lib/python3.12/dist-packages (from gradio-client==1.14.0->gradio<=5.50.0,>=4.38.0->llamafactory==0.9.5.dev0) (15.0.1)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi->llamafactory==0.9.5.dev0) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi->llamafactory==0.9.5.dev0) (0.0.4)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7.0->llamafactory==0.9.5.dev0) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7.0->llamafactory==0.9.5.dev0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7.0->llamafactory==0.9.5.dev0) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7.0->llamafactory==0.9.5.dev0) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7.0->llamafactory==0.9.5.dev0) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7.0->llamafactory==0.9.5.dev0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->llamafactory==0.9.5.dev0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->llamafactory==0.9.5.dev0) (2026.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->llamafactory==0.9.5.dev0) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic->llamafactory==0.9.5.dev0) (2.41.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->llamafactory==0.9.5.dev0) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->llamafactory==0.9.5.dev0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->llamafactory==0.9.5.dev0) (3.6.1)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->llamafactory==0.9.5.dev0) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->llamafactory==0.9.5.dev0) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->llamafactory==0.9.5.dev0) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->llamafactory==0.9.5.dev0) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->llamafactory==0.9.5.dev0) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->llamafactory==0.9.5.dev0) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->llamafactory==0.9.5.dev0) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->llamafactory==0.9.5.dev0) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->llamafactory==0.9.5.dev0) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->llamafactory==0.9.5.dev0) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->llamafactory==0.9.5.dev0) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->llamafactory==0.9.5.dev0) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->llamafactory==0.9.5.dev0) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->llamafactory==0.9.5.dev0) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->llamafactory==0.9.5.dev0) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->llamafactory==0.9.5.dev0) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.4.0->llamafactory==0.9.5.dev0) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=2.4.0->llamafactory==0.9.5.dev0) (1.5.2)
Requirement already satisfied: urllib3>=1.25 in /usr/local/lib/python3.12/dist-packages (from torchdata<=0.11.0,>=0.10.0->llamafactory==0.9.5.dev0) (2.5.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.57.0,<=5.2.0,>=4.55.0->llamafactory==0.9.5.dev0) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.57.0,<=5.2.0,>=4.55.0->llamafactory==0.9.5.dev0) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers!=4.52.0,!=4.57.0,<=5.2.0,>=4.55.0->llamafactory==0.9.5.dev0) (0.24.0)
Requirement already satisfied: docstring-parser>=0.16 in /usr/local/lib/python3.12/dist-packages (from tyro<0.9.0->llamafactory==0.9.5.dev0) (0.17.0)
Requirement already satisfied: rich>=11.1.0 in /usr/local/lib/python3.12/dist-packages (from tyro<0.9.0->llamafactory==0.9.5.dev0) (13.9.4)
Collecting shtab>=1.5.6 (from tyro<0.9.0->llamafactory==0.9.5.dev0)
  Downloading shtab-1.8.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn->llamafactory==0.9.5.dev0) (8.3.2)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn->llamafactory==0.9.5.dev0) (0.16.0)
Requirement already satisfied: termcolor in /usr/local/lib/python3.12/dist-packages (from fire->llamafactory==0.9.5.dev0) (3.3.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.12/dist-packages (from omegaconf->llamafactory==0.9.5.dev0) (4.9.3)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5.0,>=3.0->gradio<=5.50.0,>=4.38.0->llamafactory==0.9.5.dev0) (3.11)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets<=4.0.0,>=2.16.0->llamafactory==0.9.5.dev0) (3.13.5)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.24.1->gradio<=5.50.0,>=4.38.0->llamafactory==0.9.5.dev0) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.24.1->gradio<=5.50.0,>=4.38.0->llamafactory==0.9.5.dev0) (1.0.9)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.0->accelerate<=1.11.0,>=1.3.0->llamafactory==0.9.5.dev0) (1.4.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.7.0->llamafactory==0.9.5.dev0) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets<=4.0.0,>=2.16.0->llamafactory==0.9.5.dev0) (3.4.7)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=11.1.0->tyro<0.9.0->llamafactory==0.9.5.dev0) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=11.1.0->tyro<0.9.0->llamafactory==0.9.5.dev0) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.4.0->llamafactory==0.9.5.dev0) (1.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio<=5.50.0,>=4.38.0->llamafactory==0.9.5.dev0) (1.5.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<=4.0.0,>=2.16.0->llamafactory==0.9.5.dev0) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<=4.0.0,>=2.16.0->llamafactory==0.9.5.dev0) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<=4.0.0,>=2.16.0->llamafactory==0.9.5.dev0) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<=4.0.0,>=2.16.0->llamafactory==0.9.5.dev0) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<=4.0.0,>=2.16.0->llamafactory==0.9.5.dev0) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<=4.0.0,>=2.16.0->llamafactory==0.9.5.dev0) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<=4.0.0,>=2.16.0->llamafactory==0.9.5.dev0) (1.23.0)

# Imports

In [2]:
from google.colab import userdata
import wandb
import json
import os
from os.path import join
import random
from tqdm.auto import tqdm
import requests
import pandas as pd
from huggingface_hub import login
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch
device = "cuda"
torch_dtype = None
base_model_id = "Qwen/Qwen2.5-1.5B-Instruct"

In [ ]:
wandb.login(key=userdata.get('wandb'))
login(token=userdata.get('HF_TOKEN'))

/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: [wandb.login()] Using explicit session credentials for https://api.wandb.ai.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: sabryabdallah37 (sabryabdallah37-helwan-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

In [ ]:
df_training = pd.read_json('/content/drive/MyDrive/opinion-mining/train_labeled_v2.json', lines=True)
df_training.head()

,input,prediction
0,I charge it at night and skip taking the cord ...,"{""domain"":""electronics"",""aspects"":[{""term"":""Ba..."
1,I bought a HP Pavilion DV41222nr laptop and ha...,"{""domain"":""electronics"",""aspects"":[{""term"":""HP..."
2,The tech guy then said the service center does...,"{""domain"":""electronics"",""aspects"":[{""term"":""se..."
3,I investigated netbooks and saw the Toshiba NB...,"{""domain"":""electronics"",""aspects"":[{""term"":""Ne..."
4,The other day I had a presentation to do for a...,"{""domain"":""software"",""aspects"":[{""term"":""compu..."

In [15]:
df_testing = pd.read_json('/content/drive/MyDrive/opinion-mining/test_labeled_v2.json')
df_testing.head()

,input,prediction
0,"Boot time is super fast, around anywhere from ...","{""domain"":""electronics"",""aspects"":[{""term"":""Bo..."
1,tech support would not fix the problem unless ...,"{""domain"":""software"",""aspects"":[{""term"":""tech ..."
2,but in resume this computer rocks!,"{""domain"":""electronics"",""aspects"":[{""term"":""co..."
3,Set up was easy.,"{""domain"":""general"",""aspects"":[{""term"":""Set up..."
4,Did not enjoy the new Windows 8 and touchscree...,"{""domain"":""software"",""aspects"":[{""term"":""Windo..."

# Formatting Finetune Data

In [ ]:
system_message = "\n".join(["You extract structured information from text and return only valid JSON.",
                            "",
                            "No explanation No introduction No conclusion"])

In [ ]:
llm_finetunning_data = []

for i, row in df_training.iterrows():
    input = row['input']
    output = row['prediction']

    llm_finetunning_data.append({
        "system": system_message,
        "instruction": "\n".join(["Extract the domain and all aspect terms with their sentiment polarity.",
                                  "- Domains: electronics, restaurants, movies, books, software, general",
                                  "- Polarity: positive, negative, neutral",
                                  "- Extract ALL aspects mentioned in the text",
                                  "input :",
                                  input,
                                  "output format:",
                                  '{"domain":"...","aspects":[{"term":"...","polarity":"..."}, ...]}']),
        "input" : "",
        "output" : output,
        "history" : []
    })

random.Random(101).shuffle(llm_finetunning_data)

In [ ]:
len(llm_finetunning_data)

5959

In [ ]:
data_dir = "/content/drive/MyDrive/opinion-mining"

train_sample_sz = 5000

train_ds = llm_finetunning_data[:train_sample_sz]
eval_ds = llm_finetunning_data[train_sample_sz:]

os.makedirs(join(data_dir, "datasets", "llamafactory-finetune-data"), exist_ok=True)

with open(join(data_dir, "datasets", "llamafactory-finetune-data", "train.json"), "w") as dest:
    json.dump(train_ds, dest, ensure_ascii=False, default=str)

with open(join(data_dir, "datasets", "llamafactory-finetune-data", "val.json"), "w", encoding="utf8") as dest:
    json.dump(eval_ds, dest, ensure_ascii=False, default=str)

In [ ]:
join(data_dir, "datasets", "llamafactory-finetune-data", "val.json")

'/content/drive/MyDrive/opinion-mining/datasets/llamafactory-finetune-data/val.json'

# Llama-Factory Configuration

In [ ]:
# # Configure LLaMA-Factory for the new datasets

# # update /content/LLaMA-Factory/data/dataset_info.json and append
# ```
  "opinion_mining_finetune_train": {
        "file_name": "/content/drive/MyDrive/opinion-mining/datasets/llamafactory-finetune-data/train.json",
        "columns": {
            "prompt": "instruction",
            "query": "input",
            "response": "output",
            "system": "system",
            "history": "history"
        }
    },
    "opinion_mining_finetune_val": {
        "file_name": "/content/drive/MyDrive/opinion-mining/datasets/llamafactory-finetune-data/val.json",
        "columns": {
            "prompt": "instruction",
            "query": "input",
            "response": "output",
            "system": "system",
            "history": "history"
        }
    }
# ```

In [ ]:
%%writefile /content/LLaMA-Factory/examples/train_lora/news_finetune.yaml

### model
model_name_or_path: Qwen/Qwen2.5-1.5B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 32
lora_target: all

### dataset
dataset: opinion_mining_finetune_train
eval_dataset: opinion_mining_finetune_val
template: qwen
cutoff_len: 1000
##max_samples: 50
overwrite_cache: true
preprocessing_num_workers: 16

### output
resume_from_checkpoint: /content/drive/MyDrive/opinion-mining/models/checkpoint-1000
output_dir: /content/drive/MyDrive/opinion-mining/models/
logging_steps: 25
save_steps: 500
plot_loss: true
# overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
# val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 550
#disable_tqdm: true

report_to: wandb
run_name: opinion-mining-finetune-llamafactory

push_to_hub: true
export_hub_model_id: "AbdallahSabry1/opinion-mining-model-qwen2.5"
hub_private_repo: true
hub_strategy: checkpoint

Writing /content/LLaMA-Factory/examples/train_lora/news_finetune.yaml

# Finetuning

In [ ]:
!cd LLaMA-Factory/ && llamafactory-cli train /content/LLaMA-Factory/examples/train_lora/news_finetune.yaml

/usr/local/lib/python3.12/dist-packages/jieba/_compat.py:18: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
[INFO|2026-04-24 17:32:12] llamafactory.hparams.parser:505 >> Process rank: 0, world size: 1, device: cuda:0, distributed training: False, compute dtype: torch.bfloat16
[INFO|configuration_utils.py:670] 2026-04-24 17:32:13,136 >> loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-1.5B-Instruct/snapshots/989aa7980e4cf806f80c7fef2b1adb7bc71aa306/config.json
[INFO|configuration_utils.py:742] 2026-04-24 17:32:13,138 >> Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.2.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

[INFO|configuration_utils.py:670] 2026-04-24 17:32:14,821 >> loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-1.5B-Instruct/snapshots/989aa7980e4cf806f80c7fef2b1adb7bc71aa306/config.json
[INFO|configuration_utils.py:742] 2026-04-24 17:32:14,822 >> Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.2.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

[INFO|configuration_utils.py:670] 2026-04-24 17:32:14,925 >> loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-1.5B-Instruct/snapshots/989aa7980e4cf806f80c7fef2b1adb7bc71aa306/config.json
[INFO|configuration_utils.py:742] 2026-04-24 17:32:14,926 >> Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.2.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

[INFO|2026-04-24 17:32:16] llamafactory.data.loader:144 >> Loading dataset /content/drive/MyDrive/opinion-mining/datasets/llamafactory-finetune-data/train.json...
Converting format of dataset (num_proc=16): 10000 examples [00:01, 3850.26 examples/s]
[INFO|2026-04-24 17:32:17] llamafactory.data.loader:144 >> Loading dataset /content/drive/MyDrive/opinion-mining/datasets/llamafactory-finetune-data/val.json...
Converting format of dataset (num_proc=16): 1918 examples [00:00, 1044.09 examples/s]
Running tokenizer on dataset (num_proc=16): 10000 examples [00:40, 122.34 examples/s]
training example:
input_ids:
[151644, 8948, 198, 2610, 8649, 32930, 1995, 504, 1467, 323, 470, 1172, 2697, 4718, 382, 2753, 16148, 2308, 16800, 2308, 16688, 151645, 198, 151644, 872, 198, 28959, 279, 7947, 323, 678, 12893, 3793, 448, 862, 25975, 75690, 624, 12, 20751, 1735, 25, 30491, 11, 15556, 11, 9508, 11, 6467, 11, 3162, 11, 4586, 198, 12, 3651, 10748, 25, 6785, 11, 8225, 11, 20628, 198, 12, 22826, 13097, 13566, 9733, 304, 279, 1467, 198, 1355, 6260, 11209, 11, 358, 653, 537, 3535, 279, 23742, 44890, 911, 419, 10729, 624, 3006, 3561, 510, 4913, 12204, 3252, 1112, 2198, 300, 7973, 66582, 4991, 3252, 1112, 2198, 79, 72527, 3252, 1112, 14345, 2503, 13989, 151645, 198, 151644, 77091, 198, 4913, 12204, 3252, 95137, 2198, 300, 7973, 66582, 4991, 3252, 71, 499, 2198, 79, 72527, 3252, 42224, 9207, 13989, 151645, 198]
inputs:
<|im_start|>system
You extract structured information from text and return only valid JSON.

No explanation No introduction No conclusion<|im_end|>
<|im_start|>user
Extract the domain and all aspect terms with their sentiment polarity.
- Domains: electronics, restaurants, movies, books, software, general
- Polarity: positive, negative, neutral
- Extract ALL aspects mentioned in the text
input :
However, I do not understand the extraordinary hype about this restaurant.
output format:
{"domain":"...","aspects":[{"term":"...","polarity":"..."}, ...]}<|im_end|>
<|im_start|>assistant
{"domain":"restaurants","aspects":[{"term":"hype","polarity":"negative"}]}<|im_end|>

label_ids:
[-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, 4913, 12204, 3252, 95137, 2198, 300, 7973, 66582, 4991, 3252, 71, 499, 2198, 79, 72527, 3252, 42224, 9207, 13989, 151645, 198]
labels:
{"domain":"restaurants","aspects":[{"term":"hype","polarity":"negative"}]}<|im_end|>

Running tokenizer on dataset (num_proc=16): 1918 examples [00:38, 24.85 examples/s]
eval example:
input_ids:
[151644, 8948, 198, 2610, 8649, 32930, 1995, 504, 1467, 323, 470, 1172, 2697, 4718, 382, 2753, 16148, 2308, 16800, 2308, 16688, 151645, 198, 151644, 872, 198, 28959, 279, 7947, 323, 678, 12893, 3793, 448, 862, 25975, 75690, 624, 12, 20751, 1735, 25, 30491, 11, 15556, 11, 9508, 11, 6467, 11, 3162, 11, 4586, 198, 12, 3651, 10748, 25, 6785, 11, 8225, 11, 20628, 198, 12, 22826, 13097, 13566, 9733, 304, 279, 1467, 198, 1355, 6260, 3036, 979, 358, 3947, 1059, 358, 1281, 432, 264, 1459, 311, 8180, 518, 364, 641, 78, 518, 3245, 3055, 7298, 421, 537, 3055, 369, 279, 4361, 8411, 624, 3006, 3561, 510, 4913, 12204, 3252, 1112, 2198, 300, 7973, 66582, 4991, 3252, 1112, 2198, 79, 72527, 3252, 1112, 14345, 2503, 13989, 151645, 198, 151644, 77091, 198, 4913, 12204, 3252, 95137, 2198, 300, 7973, 66582, 4991, 71835, 641, 78, 2198, 79, 72527, 3252, 30487, 9207, 13989, 151645, 198]
inputs:
<|im_start|>system
You extract structured information from text and return only valid JSON.

No explanation No introduction No conclusion<|im_end|>
<|im_start|>user
Extract the domain and all aspect terms with their sentiment polarity.
- Domains: electronics, restaurants, movies, books, software, general
- Polarity: positive, negative, neutral
- Extract ALL aspects mentioned in the text
input :
And when I visit her I make it a point to eat at 'Ino at least once daily if not once for the whole trip.
output format:
{"domain":"...","aspects":[{"term":"...","polarity":"..."}, ...]}<|im_end|>
<|im_start|>assistant
{"domain":"restaurants","aspects":[{"term":"'Ino","polarity":"positive"}]}<|im_end|>

label_ids:
[-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, 4913, 12204, 3252, 95137, 2198, 300, 7973, 66582, 4991, 71835, 641, 78, 2198, 79, 72527, 3252, 30487, 9207, 13989, 151645, 198]
labels:
{"domain":"restaurants","aspects":[{"term":"'Ino","polarity":"positive"}]}<|im_end|>

[INFO|configuration_utils.py:670] 2026-04-24 17:33:43,368 >> loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-1.5B-Instruct/snapshots/989aa7980e4cf806f80c7fef2b1adb7bc71aa306/config.json
[INFO|configuration_utils.py:742] 2026-04-24 17:33:43,369 >> Model config Qwen2Config {
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "dtype": "bfloat16",
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 1536,
  "initializer_range": 0.02,
  "intermediate_size": 8960,
  "layer_types": [
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention",
    "full_attention"
  ],
  "max_position_embeddings": 32768,
  "max_window_layers": 21,
  "model_type": "qwen2",
  "num_attention_heads": 12,
  "num_hidden_layers": 28,
  "num_key_value_heads": 2,
  "pad_token_id": null,
  "rms_norm_eps": 1e-06,
  "rope_parameters": {
    "rope_theta": 1000000.0,
    "rope_type": "default"
  },
  "sliding_window": null,
  "tie_word_embeddings": true,
  "transformers_version": "5.2.0",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 151936
}

[INFO|2026-04-24 17:33:43] llamafactory.model.model_utils.kv_cache:144 >> KV cache is disabled during training.
[INFO|modeling_utils.py:710] 2026-04-24 17:33:44,241 >> loading weights file model.safetensors from cache at /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-1.5B-Instruct/snapshots/989aa7980e4cf806f80c7fef2b1adb7bc71aa306/model.safetensors
[INFO|modeling_utils.py:779] 2026-04-24 17:33:44,241 >> Will use dtype=torch.bfloat16 as defined in model's config object
[INFO|configuration_utils.py:1014] 2026-04-24 17:33:44,248 >> Generate config GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151645,
  "output_attentions": false,
  "output_hidden_states": false,
  "use_cache": false
}

Loading weights: 100% 338/338 [00:01<00:00, 178.77it/s, Materializing param=model.norm.weight]
[INFO|configuration_utils.py:967] 2026-04-24 17:33:46,569 >> loading configuration file generation_config.json from cache at /root/.cache/huggingface/hub/models--Qwen--Qwen2.5-1.5B-Instruct/snapshots/989aa7980e4cf806f80c7fef2b1adb7bc71aa306/generation_config.json
[INFO|configuration_utils.py:1014] 2026-04-24 17:33:46,569 >> Generate config GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": true,
  "eos_token_id": [
    151645,
    151643
  ],
  "pad_token_id": 151643,
  "repetition_penalty": 1.1,
  "temperature": 0.7,
  "top_k": 20,
  "top_p": 0.8
}

[INFO|dynamic_module_utils.py:406] 2026-04-24 17:33:46,673 >> Could not locate the custom_generate/generate.py inside Qwen/Qwen2.5-1.5B-Instruct.
[INFO|2026-04-24 17:33:46] llamafactory.model.model_utils.checkpointing:144 >> Gradient checkpointing enabled.
[INFO|2026-04-24 17:33:46] llamafactory.model.model_utils.attention:144 >> Using torch SDPA for faster training and inference.
[INFO|2026-04-24 17:33:46] llamafactory.model.adapter:144 >> Upcasting trainable params to float32.
[INFO|2026-04-24 17:33:46] llamafactory.model.adapter:144 >> Fine-tuning method: LoRA
[INFO|2026-04-24 17:33:46] llamafactory.model.model_utils.misc:144 >> Found linear modules: gate_proj,q_proj,v_proj,down_proj,k_proj,o_proj,up_proj
[INFO|2026-04-24 17:33:47] llamafactory.model.loader:144 >> trainable params: 36,929,536 || all params: 1,580,643,840 || trainable%: 2.3364
[WARNING|trainer_utils.py:1234] 2026-04-24 17:33:47,899 >> The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.
Traceback (most recent call last):
  File "/usr/local/bin/llamafactory-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/content/LLaMA-Factory/src/llamafactory/cli.py", line 24, in main
    launcher.launch()
  File "/content/LLaMA-Factory/src/llamafactory/launcher.py", line 157, in launch
    run_exp()
  File "/content/LLaMA-Factory/src/llamafactory/train/tuner.py", line 139, in run_exp
    _training_function(config={"args": args, "callbacks": callbacks})
  File "/content/LLaMA-Factory/src/llamafactory/train/tuner.py", line 107, in _training_function
    run_sft(model_args, data_args, training_args, finetuning_args, generating_args, callbacks)
  File "/content/LLaMA-Factory/src/llamafactory/train/sft/workflow.py", line 140, in run_sft
    train_result = trainer.train(resume_from_checkpoint=training_args.resume_from_checkpoint)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/trainer.py", line 1381, in train
    self._load_from_checkpoint(resume_from_checkpoint)
  File "/usr/local/lib/python3.12/dist-packages/transformers/trainer.py", line 3323, in _load_from_checkpoint
    raise ValueError(f"Can't find a valid checkpoint at {resume_from_checkpoint}")
ValueError: Can't find a valid checkpoint at /content/drive/opinion-mining/models/checkpoint-1000

# New Finetuned Model responses

In [4]:
model = AutoModelForCausalLM.from_pretrained(
    base_model_id,
    device_map="auto",
    torch_dtype = torch_dtype
)

tokenizer = AutoTokenizer.from_pretrained(base_model_id)

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

In [8]:
finetuned_model_id = "/content/drive/MyDrive/opinion-mining/models/checkpoint-3750"
model.load_adapter(finetuned_model_id)
model.to(device)

Loading weights:   0%|          | 0/392 [00:00<?, ?it/s]

Qwen2ForCausalLM(
  (model): Qwen2Model(
    (embed_tokens): Embedding(151936, 1536)
    (layers): ModuleList(
      (0-27): 28 x Qwen2DecoderLayer(
        (self_attn): Qwen2Attention(
          (q_proj): lora.Linear(
            (base_layer): Linear(in_features=1536, out_features=1536, bias=True)
            (lora_dropout): ModuleDict(
              (default): Identity()
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=1536, out_features=32, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=32, out_features=1536, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (k_proj): lora.Linear(
            (base_layer): Linear(in_features=1536, out_features=256, bias=True)
            (lora_dropout): ModuleDict(
              (default): Identity()
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=1536, out_features=32, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=32, out_features=256, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (v_proj): lora.Linear(
            (base_layer): Linear(in_features=1536, out_features=256, bias=True)
            (lora_dropout): ModuleDict(
              (default): Identity()
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=1536, out_features=32, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=32, out_features=256, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (o_proj): lora.Linear(
            (base_layer): Linear(in_features=1536, out_features=1536, bias=False)
            (lora_dropout): ModuleDict(
              (default): Identity()
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=1536, out_features=32, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=32, out_features=1536, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
        )
        (mlp): Qwen2MLP(
          (gate_proj): lora.Linear(
            (base_layer): Linear(in_features=1536, out_features=8960, bias=False)
            (lora_dropout): ModuleDict(
              (default): Identity()
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=1536, out_features=32, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=32, out_features=8960, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (up_proj): lora.Linear(
            (base_layer): Linear(in_features=1536, out_features=8960, bias=False)
            (lora_dropout): ModuleDict(
              (default): Identity()
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=1536, out_features=32, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=32, out_features=8960, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (down_proj): lora.Linear(
            (base_layer): Linear(in_features=8960, out_features=1536, bias=False)
            (lora_dropout): ModuleDict(
              (default): Identity()
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=8960, out_features=32, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=32, out_features=1536, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (act_fn): SiLUActivation()
        )
        (input_layernorm): Qwen2RMSNorm((1536,), eps=1e-06)
        (post_attention_layernorm): Qwen2RMSNorm((1536,), eps=1e-06)
      )
    )
    (norm): Qwen2RMSNorm((1536,), eps=1e-06)
    (rotary_emb): Qwen2RotaryEmbedding()
  )
  (lm_head): Linear(in_features=1536, out_features=151936, bias=False)
)

In [5]:
def run_qwen(prompt):
    messages = [
        {"role": "user", "content": prompt}
    ]

    inputs = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        return_tensors="pt"
    ).to(model.device)

    with torch.no_grad():
        output = model.generate(
            **inputs,
            max_new_tokens=65,
            do_sample=False,
            temperature = 0.0,
            top_k = None,
            top_p = None
        )

    result = tokenizer.decode(
        output[0][inputs["input_ids"].shape[-1]:],
        skip_special_tokens=True
    )

    return result.strip()

In [6]:
prompt = "\n".join(["You extract structured information from text and return only valid JSON.",
                            "",
                            "No explanation No introduction No conclusion",
                            "Extract the domain and all aspect terms with their sentiment polarity.",
                                  "- Domains: electronics, restaurants, movies, books, software, general",
                                  "- Polarity: positive, negative, neutral",
                                  "- Extract ALL aspects mentioned in the text",
                                  "input :",
                                  "This laptop features a high solution display and long battery life. Loved the comfortable keyboard and touch pad, also very light weight so it’s easy to carry around.",
                                  "output format:",
                                  '{"domain":"...","aspects":[{"term":"...","polarity":"..."}, ...]}'
                        ])

In [9]:
print(run_qwen(prompt))

{"domain":"electronics","aspects":[{"term":"Solution display","polarity":"positive"},{"term":"Battery life","polarity":"positive"},{"term":"Comfortable keyboard","polarity":"positive"},{"term":"Touch pad","polarity":"positive"},{"term":"Weight","polarity":"positive"}]}

In [16]:
results = []

for i, row in tqdm(df_testing.iterrows(), total=len(df_testing), desc="Running Qwen inference"):
    text = row['input']

    prompt = "\n".join(["You extract structured information from text and return only valid JSON.",
                            "",
                            "No explanation No introduction No conclusion",
                            "Extract the domain and all aspect terms with their sentiment polarity.",
                                  "- Domains: electronics, restaurants, movies, books, software, general",
                                  "- Polarity: positive, negative, neutral",
                                  "- Extract ALL aspects mentioned in the text",
                                  "input :",
                                  text,
                                  "output format:",
                                  '{"domain":"...","aspects":[{"term":"...","polarity":"..."}, ...]}'
                        ])

    prediction = run_qwen(prompt)

    results.append({
        "input": text,
        "prediction": prediction
    })

Running Qwen inference:   0%|          | 0/1572 [00:00<?, ?it/s]

In [17]:
import json

with open("finetuned_LLM_responses.json", "w") as f:
    json.dump(results, f, indent=2)

In [18]:
import shutil

shutil.copy(
    "finetuned_LLM_responses.json",
    "/content/drive/MyDrive/opinion-mining/finetuned_LLM_responses.json"
)

'/content/drive/MyDrive/opinion-mining/finetuned_LLM_responses.json'